Agronomunnity/urls.py
#Agronomunnity URL Configuration
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    #administrador
    path('admin/', admin.site.urls),
    #usuarios en general
    path('', views.index, name='index'),
    path('help', views.help, name='help'),
    path('login/', views.li, name='login'),
    path('logout/', views.lo, name='exit'),

    #Encargado de bitacora
    #Trabajador
    path("w/", views.worker, name="w"),
    path("wr/", views.workerRegister, name="wr"),
    path("wd/", views.workerDelete, name="wd"),
    path("wm/", views.workerModify, name="wm"),
    #Productor
    path('p/',views.producer, name="p"),
    path('pr/',views.producerRegister, name="pr"),
    path('pd/',views.producerDelete, name="pd"),
    path('pm/',views.producerModify, name="pm"),
    #Cuadrillas
    path('s/',views.squad, name="s"),
    path('sd/',views.squadDelete, name="sd"),
    path('sr/',views.squadRegister, name="sr"),
    path('sm/',views.squadModify, name="sm"),
    path('smd/',views.squadMemberDelete, name="smd"),
    path('smr/',views.squadMemberRegister, name="smr"),
    path('smm/',views.squadMemberModify, name="smm"),
    path('sms/',views.squadMemberSave, name="sms"),
    path('vs/',views.viewSquad, name="vs"),
    #Transporte
    path('t/',views.transport, name="t"),
    path('td/',views.transportDelete, name="td"),
    path('tr/',views.transportRegister, name="tr"),
    path('tm/',views.transportModify, name="tm"),
    #Pedido
    path('so/',views.order, name="so"),
    path('som/',views.orderModify, name="som"),
    path('sor/',views.orderRegister, name="sor"),
    path('sod/',views.orderDelete, name="sod"),
    path('vso/',views.viewOrder, name="vso"),
    #Huerta
    path('o/',views.orchard, name="o"),
    path('om/',views.orchardModify, name="om"),
    path('or/',views.orchardRegister, name="or"),
    path('od/',views.orchardDelete, name="od"),
    path('vo/',views.viewOrchard, name="vo"),
    #Viaje
    path('ct/',views.trip, name="ct"),
    path('ctr/',views.tripRegister, name="ctr"),
    path('ctd/',views.tripDelete, name="ctd"),
    path('mt/',views.myTrips, name="mt"),
    #Orden de corte
    path('co/',views.courtOrder, name="co"),
    path('com/',views.courtOrderModify, name="com"),
    path('cor/',views.courtOrderRegister, name="cor"),
    path('cod/',views.courtOrderDelete, name="cod"),
    #Cliente
    path('c/',views.client, name="c"),
    path('cm/',views.clientModify, name="cm"),
    path('cr/',views.clientRegister, name="cr"),
    path('cd/',views.clientDelete, name="cd"),
    #Calidad y calibre
    path('q/',views.quality, name="q"),
    path('qmc/',views.qualityModifyCaliber, name="qmc"),
    path('qmq/',views.qualityModifyQuality, name="qmq"),
    path('qrc/',views.qualityRegisterCaliber, name="qrc"),
    path('qdc/',views.qualityDeleteCaliber, name="qdc"),
    path('qrq/',views.qualityRegisterQuality, name="qrq"),
    path('qdq/',views.qualityDeleteQuality, name="qdq"),
    #Incidente
    path('i/',views.incident, name="i"),
    path('id/',views.incidentDelete, name="id"),
    path('ir/',views.incidentRegister, name="ir"),
    #Cambiar estatus inocuidad huerta
    path('ss/',views.safetyStatus, name="ss"),
    path('ssm/',views.safetyStatusModify, name="ssm"),
    #Finalizar Proceso
    path('ft',views.finishTrip, name="ft"),
    path('ftr/',views.finishTripRegister, name="ftr"),
    #Mis cuadrillas
    path('ms/',views.mySquad, name="ms"),
    path('msd/',views.mySquadDelete, name="msd"),
    path('msr/',views.mySquadRegister, name="msr"),
    path('msm/',views.mySquadModify, name="msm"),
    path('msmd/',views.mySquadMemberDelete, name="msmd"),
    path('msmr/',views.mySquadMemberRegister, name="msmr"),
    path('msmm/',views.mySquadMemberModify, name="msmm"),
    path('msms/',views.mySquadMemberSave, name="msms"),
    #Jefe de cuadrilla
    path("sl/", views.squadLeader, name="sl"),
    path("slr/", views.squadLeaderRegister, name="slr"),
    path("sld/", views.squadLeaderDelete, name="sld"),
    path("slm/", views.squadLeaderModify, name="slm"),
    #Solucion de incidencias
    path('si/',views.solveIncident, name="si"),
    path('sid/',views.solveIncidentDelete, name="sid"),
    path('sir/',views.solveIncidentRegister, name="sir"),
    #Precios autorizados
    path("ap/", views.authorizedPrice, name="ap"),
    path("apd/", views.authorizedPriceDelete, name="apd"),
    path("apm/", views.authorizedPriceModify, name="apm"),
    path("apr/", views.authorizedPriceRegister, name="apr"),
    #Fruta Huerta
    path("f/", views.fruit, name="f"),
    path("fd/", views.fruitDelete, name="fd"),
    path("fm/", views.fruitModify, name="fm"),
    path("fr/", views.fruitRegister, name="fr"),
    #Roles
    path("r/", views.rol, name="r"),
    path("rd/", views.rolDelete, name="rd"),
    path("rm/", views.rolModify, name="rm"),
    path("rr/", views.rolRegister, name="rr"),
    #Reportes de corte
    path("rp/", views.report, name="rp"),
    path("rpd/", views.reportDelete, name="rpd"),
    path("rpr/", views.reportRegister, name="rpr"),
    path("rdw/", views.reportDownload, name="rdw"),
    #Bitacoras
    path('cl/',views.cutLog, name="cl"),
    path('cls/',views.cutLogSearch, name="cls"),
    path('clg/',views.cutLogGenerate, name="clg"),

    #PWA
    path('', include('pwa.urls')),
    path("offline/", views.offline, name="offline"),

]



if settings.DEBUG:
    urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Agronomunnity/models.py
from django.db import models
from django.utils.timezone import now
from django.contrib.auth.models import User

class Trabajador(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    telefono = models.CharField(max_length=10, blank = True)
    rol = models.ForeignKey('RolTrabajador', on_delete=models.CASCADE)
    
    def Mostrar(self):
        return "{} {} - {}".format(self.usuario.first_name, self.usuario.last_name, self.rol.nombreRol)

    def __str__(self):
        return self.Mostrar()

    class Meta:
        verbose_name= 'Trabajador'
        verbose_name_plural= 'Trabajadores'
        db_table= 'trabajador'
        ordering= ['id']

class RolTrabajador(models.Model):
    nomenclaturaRol = models.CharField(max_length=3, blank = True)
    nombreRol = models.CharField(max_length=50, blank = True)

    def Mostrar(self):
        return "{} - {}".format(self.nomenclaturaRol, self.nombreRol)

    def __str__(self):
        return self.Mostrar()

    class Meta:
        verbose_name= 'RolTrabajador'
        verbose_name_plural= 'RolesTrabajador'
        db_table= 'roltrabajador'
        ordering= ['id']

class CamionTransporte(models.Model):
    idChoferTransporte = models.ForeignKey('Trabajador', on_delete=models.CASCADE)
    capacidadTransporte = models.CharField(max_length=20, blank = True)
    placaTransporte = models.CharField(max_length=20, blank = True)
    modeloTransporte = models.CharField(max_length=50, blank = True)
    tipoTransporte = models.CharField(max_length=50, blank = True)
    descripcionTransporte = models.CharField(max_length=200, blank = True)
    candadoTransporte = models.CharField(max_length=20, blank = True)
    estatusCamion = (
        ('C_A', 'Activo'),
        ('C_I', 'Inactivo'),
        ('C_M', 'Mantenimiento'),
    )
    estatusTransporte = models.CharField(max_length=3, choices=estatusCamion, default='Activo')
    

    def Mostrar(self):
        return "{} - {}".format(self.modeloTransporte, self.placaTransporte)

    def __str__(self):
        return self.Mostrar()

    class Meta:
        verbose_name= 'CamionTransporte'
        verbose_name_plural= 'CamionesTransporte'
        db_table= 'camiontransporte'
        ordering= ['id']

class MiembroCuadrilla(models.Model):
    nombre = models.CharField(max_length=20, blank = True)
    apellidoP = models.CharField(max_length=30, blank = True)
    apellidoM = models.CharField(max_length=30, blank = True)
    noImss = models.CharField(max_length=30, blank = True)
    idCuadrilla = models.ForeignKey('Cuadrilla', on_delete=models.CASCADE)

    def Mostrar(self):
        return "{} {} {}".format(self.nombre, self.apellidoP, self.apellidoM)

    def __str__(self):
        return self.Mostrar()

    class Meta:
        verbose_name= 'MiembroC'
        verbose_name_plural= 'MiembrosC'
        db_table= 'miembroc'
        ordering= ['id']

class Cuadrilla(models.Model):
    idGerenteCuadrilla = models.ForeignKey('Trabajador', related_name='gerente', on_delete=models.CASCADE)
    idJefeCuadrilla = models.ForeignKey('Trabajador', related_name='jefe', on_delete=models.CASCADE)
    nombreCuadrilla = models.CharField(max_length=50, blank = True)
    ubicacionCuadrilla = models.CharField(max_length=50, blank = True)
    estatus = (
        ('C_L', 'Libre'),
        ('C_O', 'Ocupada'),
    )
    estatusCuadrilla = models.CharField(max_length=3, choices=estatus, default='Activa')

    def Mostrar(self):
        return "{} - {}".format(self.nombreCuadrilla, self.get_estatusCuadrilla_display())

    def __str__(self):
        return self.Mostrar()

    class Meta:
        verbose_name= 'Cuadrilla'
        verbose_name_plural= 'Cuadrillas'
        db_table= 'cuadrilla'
        ordering= ['id']

class Productor(models.Model):
    nombre = models.CharField(max_length=20, blank = True)
    apellidoP = models.CharField(max_length=30, blank = True)
    apellidoM = models.CharField(max_length=30, blank = True)
    telefono = models.CharField(max_length=10, blank = True)

    def Mostrar(self):
        return "{} {} {}".format(self.nombre, self.apellidoP, self.apellidoM)

    def __str__(self):
        return self.Mostrar()

    class Meta:
        verbose_name= 'Productor'
        verbose_name_plural= 'Productores'
        db_table= 'productor'
        ordering= ['id']

class Huerta(models.Model):
    idProductor = models.ForeignKey('Productor', on_delete=models.CASCADE)
    nombreHuerta = models.CharField(max_length=50, blank = True)
    ubicacionHuerta = models.CharField(max_length=50, blank = True)
    localizacionHuerta = models.CharField(max_length=300, blank = True)
    claveSagarpaHuerta = models.CharField(max_length=100, blank = True)
    estatusInocuidadHuerta = models.CharField(max_length=100, blank = True)
    estatus = (
        ('H_D', 'Con fruta Disponible'),
        ('H_S', 'Sin fruta disponible'),
    )
    estatusHuerta = models.CharField(max_length=3, choices=estatus, default='Activo')

    municipio = (
        ('UPN','Uruapan'),
        ('SES','Salvador Escalante'),
        ('TAN','Tancítaro'),
        ('PER','Peribán'),
        ('TCM','Tacámbaro'),
        ('ADR','Ario de Rosales')
    )
    ubicacionHuerta = models.CharField(max_length=3, choices=municipio, default='UPN')

    fruta = (
        ('AGT', 'Aguacate'),
    )
    frutaHuerta = models.CharField(max_length=3, choices=fruta, default='AGT')

    def Mostrar(self):
        return "{}, {}".format(self.nombreHuerta, self.get_estatusHuerta_display())

    def __str__(self):
        return self.Mostrar()

    class Meta:
        verbose_name= 'Huerta'
        verbose_name_plural= 'MHuertas'
        db_table= 'huerta'
        ordering= ['id']

class Cliente(models.Model):
    nombreCliente = models.CharField(max_length=40, blank = True)
    apellidoPCliente = models.CharField(max_length=20, blank = True) 
    apellidoMCliente = models.CharField(max_length=20, blank = True)
    rfcCliente = models.CharField(max_length=20, blank = True)

    def Mostrar(self):
        return "{} {} {}".format(self.nombreCliente, self.apellidoPCliente, self.apellidoMCliente)

    def __str__(self):
        return self.Mostrar()

    class Meta:
        verbose_name= 'Cliente'
        verbose_name_plural= 'Clientes'
        db_table= 'cliente'
        ordering= ['id']

class Pedido(models.Model):
    idTrabajador = models.ForeignKey('Trabajador', on_delete=models.CASCADE)
    idCliente = models.ForeignKey('Cliente', on_delete=models.CASCADE)
    numeroPedido = models.CharField(max_length=20, blank = True)
    fechaPedido = models.DateField()
    totalKilosPedido = models.IntegerField(blank=True)
    totalPalletsPedido = models.IntegerField(blank=True)
    destinoPedido = models.CharField(max_length=50, blank = True)
    observacionPedido = models.CharField(max_length=500, blank = True)
    mercado = (
        ('M_N', 'Nacional'),
        ('M_E', 'Exportación'),
        ('M_O', 'Otros destinos'),
    )
    mercadoPedido = models.CharField(max_length=3, choices=mercado, default='Nacional')
    estatus = (
        ('P_I', 'Iniciado'),
        ('P_O', 'Ordenado'),
        ('P_V', 'En viaje'),
        ('P_C', 'Completado'),
    )
    estatusPedido = models.CharField(max_length=3, choices=estatus, default='Pendiente')

    def Mostrar(self):
        return "Pedido: {} - {}".format(self.numeroPedido, self.get_estatusPedido_display())

    def __str__(self):
        return self.Mostrar()

    class Meta:
        verbose_name= 'Pedido'
        verbose_name_plural= 'Pedidos'
        db_table= 'pedido'
        ordering= ['id']

class Calibre(models.Model):
    numCalibre = models.IntegerField(blank=True)
    descripcionCalibre = models.CharField(max_length=500, blank = True)

    def Mostrar(self):
        return "Calibre: {}".format(self.numCalibre)

    def __str__(self):
        return self.Mostrar()

    class Meta:
        verbose_name= 'Calibre'
        verbose_name_plural= 'Calibres'
        db_table= 'calibre'
        ordering= ['id']

class Calidad(models.Model):
    descripcionCalidad = models.CharField(max_length=500, blank = True)
    numCalidad = models.IntegerField(blank=True)

    def Mostrar(self):
        return "Calidad: {}".format(self.numCalidad)

    def __str__(self):
        return self.Mostrar()

    class Meta:
        verbose_name= 'Calidad'
        verbose_name_plural= 'Calidades'
        db_table= 'calidad'
        ordering= ['id']

class PedidoCalibreCalidad(models.Model):
    idPedido = models.ForeignKey('Pedido', on_delete=models.CASCADE)
    idCalibre = models.ForeignKey('Calibre', on_delete=models.CASCADE)
    idCalidad = models.ForeignKey('Calidad', on_delete=models.CASCADE)
    cantidadCC = models.IntegerField(blank=True)

    def Mostrar(self):
        return "Pedido: {} - {} kg.".format(self.idPedido, self.cantidadCC)

    def __str__(self):
        return self.Mostrar()

    class Meta:
        verbose_name= 'PedidoCalibreCalidad'
        verbose_name_plural= 'PedidosCalibreCalidad'
        db_table= 'pedidocalibrecalidad'
        ordering= ['id']

class OrdenCorte(models.Model):
    fechaOrden = models.DateField()
    numeroOrden = models.CharField(max_length=20, blank = True)
    corte = (
        ('','(Seleccione)'),
        ('AVN', 'Aventajado'),
        ('FLC', 'Flor loca'),
    )
    tipoCorte = models.CharField(max_length=3, choices=corte, default='')
    idPedido = models.OneToOneField(Pedido, on_delete=models.CASCADE, null=True)
    idHuerta = models.ForeignKey('Huerta', on_delete=models.CASCADE, null=True)

    def Mostrar(self):
        return "Orden: {} - {}".format(self.numeroOrden, self.fechaOrden)

    def __str__(self):
        return self.Mostrar()

    class Meta:
        verbose_name= 'OrdenCorte'
        verbose_name_plural= 'OrdenesCorte'
        db_table= 'ordencorte'
        ordering= ['id']

class ViajeCorte(models.Model):
    fechaViaje = models.DateField()

Agronomunnity/templates/user_enc_rec/finishTrip.html
{% extends 'layouts/base.html' %}

{% block title %}Viajes en proceso{% endblock %}

{% block content %}
    <div class="mx-5 align-items-center justify-content-center">
        <div class="row text-center justify-content-center align-items-center py-3">
            <div class="text-2 col-6 text-md-start">
                <h3 class="py-3">Viajes en proceso</h3>
            </div>
            <div class="col-6">
                <input type="text" id="searchInput" class="form-control" placeholder="Buscar viajes...">
            </div>
        </div>
        <div class="d-flex justify-content-center align-items-center">
            <div class="alert alert-danger rounded-pill w-lg-25 text-xs text-center" role="alert">
                <i class="fa-solid fa-info-circle mr-2"></i>Revisa bien los detalles antes de finalizar el proceso, por favor.
            </div>
        </div>
        {% if nvc > 0 %}
            <div class="table-responsive">
                <table id="example" class="table table-striped text-center" style="width:100%">
                    <thead>
                        <tr>
                            <th>No. viaje</th>
                            <th>Cuadrilla</th>
                            <th>Huerta</th>
                            <th>Estado</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for a in vc %}
                            <tr>
                                <td>{{a.idOrdenCorte.idPedido.numeroPedido}}</td>
                                <td>{{a.idCuadrilla.nombreCuadrilla}}</td>
                                <td>{{a.idHuerta.nombreHuerta}}</td>
                                {% if a.idOrdenCorte.idPedido.estatusPedido == 'P_V' %}
                                    <td class="text-xs"><i class="fa-solid fa-battery-three-quarters text-info"></i><br>En viaje</td>
                                {% elif a.idOrdenCorte.idPedido.estatusPedido == 'P_P' %}
                                    <td class="text-xs"><i class="fa-solid fa-battery text-success"></i><br>Completado</td>
                                {% endif %}
                                <td>
                                    <button type="submit" class="btn text-xs" data-bs-toggle="modal" data-bs-target="#detalles{{a.id}}">
                                        <i class="nav-icon fa-solid fa-calendar-check"></i>
                                    </button>
                                    <div class="modal fade" id="detalles{{a.id}}">
                                        <div class="modal-dialog modal-dialog-centered">
                                          <div class="modal-content">
                                            <div class="modal-header">
                                              <h5 class="modal-title">Panel de detalles</h5>
                                              <i class="fa-solid fa-xmark fs-5" data-bs-dismiss="modal"></i>
                                            </div>
                                            <div class="modal-body">
                                                <div class="row">
                                                    <div class="col-md-12">
                                                        <button type="button" class="btn text-xs bg-success px-5 mb-3" data-bs-toggle="modal" data-bs-target="#confirmar{{a.id}}">
                                                            <i class="nav-icon fas fa-calendar-check text-light mr-2"></i>Confirmar de recibido
                                                        </button>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-md-6">
                                                        <p class="fw-bold mb-0">Orden número:</p>
                                                        <p>{{a.idOrdenCorte.numeroOrden}}</p>
                                                    </div>
                                                    <div class="col-md-6">
                                                        <p class="fw-bold mb-0">Fecha:</p>
                                                        <p>{{a.fechaViaje}}</p>
                                                    </div>
                                                </div>
                                              <div class="row">
                                                <div class="col-md-12">
                                                    <p class="fw-bold mb-0">Para el cliente:</p>
                                                    <p>{{a.idOrdenCorte.idPedido.idCliente.nombreCliente}} {{a.idOrdenCorte.idPedido.idCliente.apellidoPCliente}} {{a.idOrdenCorte.idPedido.idCliente.apellidoMCliente}}</p>
                                                </div>
                                              </div>
                                              <div class="row">
                                                <div class="col-md-6">
                                                    <p class="fw-bold mb-0">Contiene:</p>
                                                    <p>{{a.idOrdenCorte.idPedido.totalPalletsPedido}} pallets.</p>
                                                </div>
                                                <div class="col-md-6">
                                                    <p class="fw-bold mb-0">Destino:</p>
                                                    <p>{{a.idOrdenCorte.idPedido.destinoPedido}}</p>
                                                </div>
                                              </div>
                                              <div class="row">
                                                <div class="col-md-12">
                                                  <p class="fw-bold mb-0">Generada por:</p>
                                                  <p>{{a.idOrdenCorte.idPedido.idTrabajador.usuario.first_name}} {{a.idOrdenCorte.idPedido.idPedido.idTrabajador.usuario.last_name}}</p>
                                                </div>
                                              </div>
                                              <div class="row">
                                                <div class="col-md-6">
                                                  <p class="fw-bold mb-0">Kilos:</p>
                                                  <p>{{a.idOrdenCorte.idPedido.totalKilosPedido}}</p>
                                                </div>
                                                <div class="col-md-6">
                                                  <p class="fw-bold mb-0">Mercado:</p>
                                                  <p>{{a.idOrdenCorte.idPedido.get_mercadoPedido_display}}</p>
                                                </div>
                                              </div>
                                              <div class="row">
                                                <div class="align-items-center">
                                                    <p class="fw-bold mb-2">Contiene los siguientes tipos:</p>
                                                </div>
                                                <div class="col-12 table-responsive" >
                                                    <table id="tabla" class="table table-striped text-center" style="width:100%">
                                                        <thead>
                                                            <tr class="align-items-center">
                                                                <th>Calibre</th>
                                                                <th>Calidad</th>
                                                                <th>Kg</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            {% for b in pcc %}
                                                                {% if a.idOrdenCorte.idPedido.id == b.idPedido.id %}
                                                                    <tr>
                                                                        <td>{{b.idCalibre.numCalibre}}</td>
                                                                        <td>{{b.idCalidad.numCalidad}}</td>
                                                                        <td>{{b.cantidadCC}}</td>
                                                                    </tr>
                                                                {% endif %}
                                                            {% endfor %}
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>
                                            </div>
                                          </div>
                                        </div>
                                      </div>
                                    <div class="modal fade" id="confirmar{{a.id}}">
                                        <div class="modal-dialog text-center">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h1 class="fs-6">¿Seguro que quieres marcar como recibido este viaje?</h1>
                                                    <i class="fa-solid fa-xmark fs-5" data-bs-dismiss="modal"></i>
                                                </div>
                                                <div class="modal-body">
                                                    <div class="text-center mx-5 rounded">
                                                        <p class="fs-10">*Revisa que todo este en orden para que no halla complicaciones con revisiones futuras.</p>
                                                    </div>
                                                    <div class="text-center d-inline-block">
                                                        <p class="form-floating">
                                                            <form method="POST" enctype="multipart/form-data">
                                                                {% csrf_token %}
                                                                
                                                                        <input type="hidden" name="Id" value="agregar">
                                                                        <input type="hidden" name="Viaje" value={{a.id}}>
                                                                        <button type="submit" class="btn btn-success">
                                                                            <i class="nav-icon fas fa-calendar-check mr-2"></i>Confirmar
                                                                        </button>
                                                                    </p>
                                                                </div>
                                                            </form>
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        {% else %}
            <div class="card text-center shadow rounded mx-5">
                <div class="card-body text-center">
                    <h5 class="card-titl">No hay viajes en curso.</h5>
                    <img src="/static/assets/img/icons/no-camion.png" width="70">
                    <p class="card-text">Actualmente no hay viajes de corte en curso. Espera hasta que el encargado asigne nuevos viajes.</p>
                </div>
            </div>
        {% endif %}

{% endblock content %}

Agronomunnity/templates/user_enc_rec/sidenav.html
<aside class="main-sidebar sidebar-light-primary elevation-3 position-fixed">
  <!--Usuario-->
  <a href="" class="brand-link shadow" style="background:#4CAF50">
    <div class="row my-n1 align-items-center">
      <div class="col-3 text-start">
        <img src="/static/assets/img/icons/user-icon.svg" alt="logo" width="30" class="ml-3 rounded-circle"/>
      </div>
      <div class="col-8 text-start text-sm">
        <span class="brand-text text-light">-{{request.user.trabajador.usuario.first_name}}-</span>
        <br><span class="brand-text text-light">{{request.user.trabajador.rol.nombreRol}}</span>
      </div>
  </div>
  </a>
  <!-- Sidebar -->
  <div class="sidebar">
      <nav class="mt-2">
          <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu">
            <li class="nav-item rounded" {% if request.resolver_match.url_name == 'index' %} style='background-color: #c9e7cb' {% endif %}>
              <a href="{% url 'index' %}" class="nav-link inactive">
                  <i class="nav-icon fa-solid fa-house"></i>
                  <p>Inicio</p>
              </a>
            </li>
            <li class="nav-item rounded" {% if request.resolver_match.url_name == 'ft' %} style='background-color: #c9e7cb' {% endif %}>
              <a href="{% url 'ft' %}" class="nav-link inactive">
                  <i class="nav-icon fa-solid fa-truck-fast"></i>
                  <p>Viajes en curso</p>
              </a>
            </li>
            <li class="nav-item rounded" {% if request.resolver_match.url_name == 'vso' %} style='background-color: #c9e7cb' {% endif %}>
              <a href="{% url 'vso' %}" class="nav-link inactive">
                  <i class="nav-icon fa-solid fa-bar-chart"></i>
                  <p>Pedidos</p>
              </a>
            </li>
            <li class="nav-item rounded" {% if request.resolver_match.url_name == 'i' %} style='background-color: #c9e7cb' {% endif %}>
              <a href="{% url 'i' %}" class="nav-link inactive">
                  <i class="nav-icon fa-solid fa-circle-exclamation"></i>
                  <p>Incidencias</p>
              </a>
            </li>
            <li class="nav-item rounded" {% if request.resolver_match.url_name == 'help' %} style='background-color: #c9e7cb' {% endif %}>
              <a href="{% url 'help' %}" class="nav-link inactive">
                  <i class="nav-icon fa-solid fa-question-circle"></i>
                  <p>Ayuda</p>
              </a>
            </li>
            <li class="nav-item">
              <a href={% url 'exit' %} class="nav-link inactive text-danger">
                  <i class="nav-icon fa-solid fa-sign-out"></i>
                  <p>Cerrar Sesión</p>
              </a>
            </li>
          </ul>
      </nav>
  </div>
</aside>